name: docs
dependencies:
    # Base depends
  - python=3.8
  - pip

    # Package depends
  - numpy
  - matplotlib
  - pandas

    # Pip-only installs
  - pip:
    - sphinx==6.0.0
    - sphinx-autoapi==2.1.1
    - https://github.com/revitron/revitron-sphinx-theme/archive/master.zip
    - beautifulsoup4
    - geopy
