name: docs
channels:
  - conda-forge
dependencies:
    # Base depends
  - python
  - pip

    # Package depends
  - numpy
  - matplotlib
  - pandas
  - sphinx=6.0.0

    # Pip-only installs
  - pip:
    - sphinx-autoapi
    - https://github.com/revitron/revitron-sphinx-theme/archive/master.zip
    - beautifulsoup4
    - geopy
